version: "3.6"
services:
  redis_master:
    image: redis
    container_name: redis_master
    restart: always
    command: redis-server --port 6379 --requirepass master_pwd --appendonly yes
    ports:
      - 16379:6379

  redis_slave_1:
    image: redis
    container_name: redis_slave_1
    restart: always
    command: redis-server --slaveof redis_master 6379 --port 6379 --requirepass slave_pwd --masterauth master_pwd --appendonly yes
    ports:
      - 26379:6379

  redis_slave_2:
    image: redis
    container_name: redis_slave_2
    restart: always
    command: redis-server --slaveof redis_master 6379 --port 6379 --requirepass slave_pwd --masterauth master_pwd --appendonly yes
    ports:
      - 36379:6379